name: Clojure CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Java JDK
      uses: actions/setup-java@v3.5.0
      with:
        distribution: "temurin"
        java-version: 17
    - name: Install Clojure CLI
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        tools-deps: 1.10.1.693
    - name: Build JS
      run: clojure -A:prod:play-cljc

    - name: Copy Files
      run: |
        mkdir ../out
        mkdir ../out/resources
        mkdir ../out/resources/public
        cp -r resources/public/* ../out/resources/public
        cp -r server/* ../out

    - name: Configure Git
      run: |
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "Automation"

    - name: Build Pages
      run: |
        git switch gh-pages
        rm -r *
        cp -r ../out/resources/public/* ./
        git add -u
        git add -v *
        git diff --staged --quiet && echo "No changes." || git commit -a -v -m "Build Pages" && git push -v

    - name: Deploy Server
      run: |
        git switch server-deploy
        rm -r *
        cp -r ../out/* ./
        git add -u
        git add -v *
        git diff --staged --quiet && echo "No changes." || git commit -a -v -m "Deploy Server" && git push -v
