name: Clojure CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.2
      with:
        java-version: 1.15
    - name: Install Clojure CLI
      uses: DeLaGuardo/setup-clojure@2.0
      with:
        tools-deps: 1.10.1.693
    - name: Build JS
      run: clojure -A:prod:play-cljc
    - name: Build Pages
      run: |
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config user.name "Automation"
        git switch gh-pages
        mv resources/public ../out
        rm -r *
        mv ../out/* ./
        git add -u
        git add -v *
        git diff --staged --quiet && echo "No changes." || git commit -a -v -m "Build Pages" && git push -v
